---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1":
    get:
      summary: Return message
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Return the backend challenge message
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: REST Back-end Challenge 20201209 Running
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
  "/api/v1/import_launchers":
    get:
      summary: Import launchers
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Import launchers data assyncronously
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Running launchers import asyncronously
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
  "/api/v1/launchers":
    get:
      summary: List launchers
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Return the list of launchers. 100 per page
      responses:
        '200':
          description: Successful
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
    post:
      summary: Create launcher
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Create a launcher
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                  launch_library_id:
                    type: string
                  slug:
                    type: string
                  name:
                    type: string
                  net:
                    type: string
                  window_end:
                    type: string
                  window_start:
                    type: string
                  inhold:
                    type: boolean
                  tbdtime:
                    type: boolean
                  tbddate:
                    type: boolean
                  probability:
                    type: integer
                  holdreason:
                    type: string
                  failreason:
                    type: string
                  hashtag:
                    type: string
                  webcast_live:
                    type: boolean
                  image:
                    type: string
                  infographic:
                    type: string
                  imported_t:
                    type: string
                  import_status:
                    type: string
                  launch_service_provider:
                    type: hash
                  mission:
                    type: hash
                  pad:
                    type: hash
                  program:
                    type: array
                  rocket:
                    type: hash
                  status:
                    type: hash
                  import_id:
                    type: string
                  last_import_code:
                    type: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Name can't be blank
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/launch"
  "/api/v1/launchers/{launcher_id}":
    parameters:
    - name: launcher_id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show launcher
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Return an secific launcher by id
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                  launch_library_id:
                    type: string
                  slug:
                    type: string
                  name:
                    type: string
                  net:
                    type: string
                  window_end:
                    type: string
                  window_start:
                    type: string
                  inhold:
                    type: boolean
                  tbdtime:
                    type: boolean
                  tbddate:
                    type: boolean
                  probability:
                    type: integer
                  holdreason:
                    type: string
                  failreason:
                    type: string
                  hashtag:
                    type: string
                  webcast_live:
                    type: boolean
                  image:
                    type: string
                  infographic:
                    type: string
                  imported_t:
                    type: string
                  import_status:
                    type: string
                  launch_service_provider:
                    type: hash
                  mission:
                    type: hash
                  pad:
                    type: hash
                  program:
                    type: array
                  rocket:
                    type: hash
                  status:
                    type: hash
                  import_id:
                    type: string
                  last_import_code:
                    type: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
        '404':
          description: Return message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Launcher not found
    put:
      summary: Update launcher
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Update an specific launcher
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                  launch_library_id:
                    type: string
                  slug:
                    type: string
                  name:
                    type: string
                  net:
                    type: string
                  window_end:
                    type: string
                  window_start:
                    type: string
                  inhold:
                    type: boolean
                  tbdtime:
                    type: boolean
                  tbddate:
                    type: boolean
                  probability:
                    type: integer
                  holdreason:
                    type: string
                  failreason:
                    type: string
                  hashtag:
                    type: string
                  webcast_live:
                    type: boolean
                  image:
                    type: string
                  infographic:
                    type: string
                  imported_t:
                    type: string
                  import_status:
                    type: string
                  launch_service_provider:
                    type: hash
                  mission:
                    type: hash
                  pad:
                    type: hash
                  program:
                    type: array
                  rocket:
                    type: hash
                  status:
                    type: hash
                  import_id:
                    type: string
                  last_import_code:
                    type: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
        '404':
          description: Return message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Launcher not found
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Name can't be blank
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/launch"
    delete:
      summary: Delete launcher
      tags:
      - Launchers
      security:
      - bearer_auth: []
      description: Delete an specficic launcher
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                  launch_library_id:
                    type: string
                  slug:
                    type: string
                  name:
                    type: string
                  net:
                    type: string
                  window_end:
                    type: string
                  window_start:
                    type: string
                  inhold:
                    type: boolean
                  tbdtime:
                    type: boolean
                  tbddate:
                    type: boolean
                  probability:
                    type: integer
                  holdreason:
                    type: string
                  failreason:
                    type: string
                  hashtag:
                    type: string
                  webcast_live:
                    type: boolean
                  image:
                    type: string
                  infographic:
                    type: string
                  imported_t:
                    type: string
                  import_status:
                    type: string
                  launch_service_provider:
                    type: hash
                  mission:
                    type: hash
                  pad:
                    type: hash
                  program:
                    type: array
                  rocket:
                    type: hash
                  status:
                    type: hash
                  import_id:
                    type: string
                  last_import_code:
                    type: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
        '404':
          description: Return message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Launcher not found
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Name can't be blank
  "/api/v1/get_token":
    get:
      summary: Token
      tags:
      - Token
      responses:
        '200':
          description: Successful
servers:
- url: http://localhost:3000
components:
  schemas:
    launch:
      type: object
      properties:
        url:
          type: string
        launch_library_id:
          type: string
        slug:
          type: string
        name:
          type: string
        net:
          type: string
        window_end:
          type: string
        window_start:
          type: string
        inhold:
          type: boolean
        tbdtime:
          type: boolean
        tbddate:
          type: boolean
        probability:
          type: integer
        holdreason:
          type: string
        failreason:
          type: string
        hashtag:
          type: string
        webcast_live:
          type: boolean
        image:
          type: string
        infographic:
          type: string
        imported_t:
          type: string
        import_status:
          type: string
        launch_service_provider:
          type: hash
        mission:
          type: hash
        pad:
          type: hash
        program:
          type: array
        rocket:
          type: hash
        status:
          type: hash
        import_id:
          type: string
        last_import_code:
          type: string
    token:
      type: object
      properties:
        key:
          type: string
        expiration:
          type: date
  securitySchemes:
    bearer_auth:
      type: http
      name: Token Authentication
      scheme: bearer
